# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'URLRouter-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URLRouter-Example
  pod 'URLRouter', :path => '../', :subspecs => ['Matcher', 'Router', 'Navigator'], :testspecs => ['Tests']

  target 'URLRouter-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
